#!/usr/bin/env node
/**
 * Emits per-locale string-table chunks from each app's i18n aggregator
 * (apps/<app>/src/renderer/i18n/strings.ts). The renderer then loads only the
 * active locale's chunk at boot instead of parsing every language's literals,
 * which shaves hundreds of KB of parse off each editor's entry bundle.
 *
 * Output: apps/<app>/src/renderer/i18n/generated/<lang>.ts — gitignored, rebuilt
 * on every `npm run predev` / `build:all` (chained in the root scripts), so
 * upstream syncs of the source tables never conflict with generated files.
 *
 * Run with tsx (imports the TypeScript aggregators): npx tsx fork/tools/emit-locales.mjs
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'

const root = join(import.meta.dirname, '..', '..')

for (const app of ['docs', 'sheets', 'slides', 'pdf', 'markdown']) {
  const i18nDir = join(root, 'apps', app, 'src', 'renderer', 'i18n')
  let strings
  try {
    const mod = await import(pathToFileURL(join(i18nDir, 'strings.ts')).href)
    strings = mod.strings
  } catch (err) {
    console.warn(`${app}: skipped (${err instanceof Error ? err.message : err})`)
    continue
  }
  const outDir = join(i18nDir, 'generated')
  mkdirSync(outDir, { recursive: true })
  for (const [lang, dict] of Object.entries(strings)) {
    writeFileSync(
      join(outDir, `${lang}.ts`),
      `// generated by fork/tools/emit-locales.mjs — do not edit\n` +
        `export default ${JSON.stringify(dict, null, 1)} satisfies Record<string, string>\n`,
    )
  }
  console.log(`${app}: ${Object.keys(strings).length} locales -> i18n/generated/`)
}