import type { Activity, Company, Contact, Deal } from '../shared/types'

export const SEED_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    name: 'Acme Global Technologies',
    domain: 'acme.tech',
    industry: 'Enterprise Software',
    size: '500-1000',
    website: 'https://acme.tech',
    city: 'San Francisco',
    country: 'United States',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'comp-2',
    name: 'Nexus Media Labs',
    domain: 'nexusmedia.io',
    industry: 'Digital Marketing',
    size: '50-200',
    website: 'https://nexusmedia.io',
    city: 'London',
    country: 'United Kingdom',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'comp-3',
    name: 'Helios Clean Energy',
    domain: 'heliosenergy.de',
    industry: 'Renewable Energy',
    size: '200-500',
    website: 'https://heliosenergy.de',
    city: 'Berlin',
    country: 'Germany',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'comp-4',
    name: 'Vertex Financial Group',
    domain: 'vertexfinance.com',
    industry: 'FinTech',
    size: '1000+',
    website: 'https://vertexfinance.com',
    city: 'Singapore',
    country: 'Singapore',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
]

export const SEED_CONTACTS: Contact[] = [
  {
    id: 'cont-1',
    name: 'Sarah Chen',
    email: 'sarah.chen@acme.tech',
    phone: '+1 (415) 882-9102',
    title: 'Chief Technology Officer',
    companyId: 'comp-1',
    companyName: 'Acme Global Technologies',
    tags: ['Decision Maker', 'VIP', 'Enterprise'],
    status: 'active',
    createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'cont-2',
    name: 'Marcus Sterling',
    email: 'marcus@nexusmedia.io',
    phone: '+44 20 7946 0912',
    title: 'Head of Operations',
    companyId: 'comp-2',
    companyName: 'Nexus Media Labs',
    tags: ['Marketing', 'High Potential'],
    status: 'active',
    createdAt: new Date(Date.now() - 22 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'cont-3',
    name: 'Dr. Elena Rostova',
    email: 'elena@heliosenergy.de',
    phone: '+49 30 1234 5678',
    title: 'VP Engineering',
    companyId: 'comp-3',
    companyName: 'Helios Clean Energy',
    tags: ['Engineering', 'Strategic'],
    status: 'active',
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'cont-4',
    name: 'David Vance',
    email: 'dvance@vertexfinance.com',
    phone: '+65 6789 0123',
    title: 'Managing Director',
    companyId: 'comp-4',
    companyName: 'Vertex Financial Group',
    tags: ['Finance', 'Enterprise'],
    status: 'lead',
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
]

export const SEED_DEALS: Deal[] = [
  {
    id: 'deal-1',
    name: 'Global Suite Migration & Deployment',
    companyId: 'comp-1',
    companyName: 'Acme Global Technologies',
    contactId: 'cont-1',
    contactName: 'Sarah Chen',
    amount: 120000,
    stage: 'negotiation',
    probability: 85,
    expectedCloseDate: '2026-10-15',
    notes: 'Final contract terms in review with legal team. Focused on data privacy and local-first execution.',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'deal-2',
    name: 'AI Automation Workflows Package',
    companyId: 'comp-2',
    companyName: 'Nexus Media Labs',
    contactId: 'cont-2',
    contactName: 'Marcus Sterling',
    amount: 45000,
    stage: 'proposal',
    probability: 60,
    expectedCloseDate: '2026-10-30',
    notes: 'Demo presented to Marcus last Friday. Positive response to office document generation.',
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'deal-3',
    name: 'Clean Tech Analytics Pipeline',
    companyId: 'comp-3',
    companyName: 'Helios Clean Energy',
    contactId: 'cont-3',
    contactName: 'Dr. Elena Rostova',
    amount: 85000,
    stage: 'won',
    probability: 100,
    expectedCloseDate: '2026-09-01',
    notes: 'Closed and signed! Onboarding kick-off scheduled next Monday.',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'deal-4',
    name: 'Enterprise Security Compliance Integration',
    companyId: 'comp-4',
    companyName: 'Vertex Financial Group',
    contactId: 'cont-4',
    contactName: 'David Vance',
    amount: 95000,
    stage: 'qualified',
    probability: 40,
    expectedCloseDate: '2026-11-20',
    notes: 'Discovery call completed. Requirement doc needed before proposal.',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'deal-5',
    name: 'Document Workspace Pilot',
    companyId: 'comp-2',
    companyName: 'Nexus Media Labs',
    contactId: 'cont-2',
    contactName: 'Marcus Sterling',
    amount: 18000,
    stage: 'lead',
    probability: 25,
    expectedCloseDate: '2026-12-05',
    notes: 'Inbound inquiry via website.',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
]

export const SEED_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    dealId: 'deal-1',
    contactId: 'cont-1',
    type: 'meeting',
    title: 'Executive alignment call with Sarah Chen',
    description: 'Reviewed security whitepaper and negotiated SLA terms. Agreed on 24/7 dedicated tier.',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    completed: true,
  },
  {
    id: 'act-2',
    dealId: 'deal-2',
    contactId: 'cont-2',
    type: 'email',
    title: 'Sent formal proposal document',
    description: 'Shared custom proposal created with Zanostack Docs.',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    completed: true,
  },
  {
    id: 'act-3',
    dealId: 'deal-4',
    contactId: 'cont-4',
    type: 'task',
    title: 'Draft compliance questionnaire response',
    description: 'Need to complete SOC2 and ISO27001 self-attestation answers for David.',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    completed: false,
  },
]
