import type { Activity, Company, Contact, Deal } from '../shared/types'

export const SEED_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    name: 'Thabo Engineering (Pty) Ltd',
    domain: 'thaboeng.co.za',
    industry: 'Civil & Electrical Engineering',
    size: '50-200',
    website: 'https://thaboeng.co.za',
    city: 'Johannesburg',
    country: 'South Africa',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'comp-2',
    name: 'Lethabo Infrastructure (Pty) Ltd',
    domain: 'lethabo.co.za',
    industry: 'Construction',
    size: '200-500',
    website: 'https://lethabo.co.za',
    city: 'Pretoria',
    country: 'South Africa',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'comp-3',
    name: 'Sekhukhune Water Services (Pty) Ltd',
    domain: 'sekhukhunewater.co.za',
    industry: 'Water & Sanitation',
    size: '50-200',
    website: 'https://sekhukhunewater.co.za',
    city: 'Polokwane',
    country: 'South Africa',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'comp-4',
    name: 'Ekurhuleni Facilities Group (Pty) Ltd',
    domain: 'ekurhulenifacilities.co.za',
    industry: 'Facilities Management',
    size: '200-500',
    website: 'https://ekurhulenifacilities.co.za',
    city: 'Germiston',
    country: 'South Africa',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
]

export const SEED_CONTACTS: Contact[] = [
  {
    id: 'cont-1',
    name: 'Naledi Mokoena',
    email: 'naledi@thaboeng.co.za',
    phone: '+27 11 482 3067',
    title: 'Contracts Manager',
    companyId: 'comp-1',
    companyName: 'Thabo Engineering (Pty) Ltd',
    tags: ['Decision Maker', 'Tendering', 'Enterprise'],
    status: 'active',
    createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'cont-2',
    name: 'Pieter van der Merwe',
    email: 'pieter@lethabo.co.za',
    phone: '+27 12 346 8820',
    title: 'Head of Operations',
    companyId: 'comp-2',
    companyName: 'Lethabo Infrastructure (Pty) Ltd',
    tags: ['Construction', 'High Potential'],
    status: 'active',
    createdAt: new Date(Date.now() - 22 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'cont-3',
    name: 'Sipho Dlamini',
    email: 'sipho@sekhukhunewater.co.za',
    phone: '+27 13 752 4409',
    title: 'Managing Director',
    companyId: 'comp-3',
    companyName: 'Sekhukhune Water Services (Pty) Ltd',
    tags: ['Water Services', 'Strategic'],
    status: 'active',
    createdAt: new Date(Date.now() - 18 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'cont-4',
    name: 'Ayesha Patel',
    email: 'ayesha@ekurhulenifacilities.co.za',
    phone: '+27 11 873 2215',
    title: 'Finance Executive',
    companyId: 'comp-4',
    companyName: 'Ekurhuleni Facilities Group (Pty) Ltd',
    tags: ['Finance', 'Enterprise'],
    status: 'lead',
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
]

export const SEED_DEALS: Deal[] = [
  {
    id: 'deal-1',
    name: 'Municipal Water Reticulation Bid — DWS/RFP-2026/0034',
    companyId: 'comp-1',
    companyName: 'Thabo Engineering (Pty) Ltd',
    contactId: 'cont-1',
    contactName: 'Naledi Mokoena',
    amount: 1850000,
    stage: 'negotiation',
    probability: 85,
    owner: 'Thandi Nkosi',
    nextStep: 'Finalize B-BBEE and COIDA returnables',
    expectedCloseDate: '2026-11-30',
    notes:
      'Final compliance matrix review done — COIDA letter renewed, awaiting signed SBD 4 before submission.',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'deal-2',
    name: 'Tender Compliance Automation Package',
    companyId: 'comp-2',
    companyName: 'Lethabo Infrastructure (Pty) Ltd',
    contactId: 'cont-2',
    contactName: 'Pieter van der Merwe',
    amount: 650000,
    stage: 'proposal',
    probability: 60,
    owner: 'Karabo Molefe',
    nextStep: 'Present bid-readiness pilot results',
    expectedCloseDate: '2026-10-30',
    notes:
      'Demo of the RFP shredder and compliance matrix went well — they want vault expiry tracking for the whole tender team.',
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'deal-3',
    name: 'Invoice Manager & Workflow Automation',
    companyId: 'comp-3',
    companyName: 'Sekhukhune Water Services (Pty) Ltd',
    contactId: 'cont-3',
    contactName: 'Sipho Dlamini',
    amount: 420000,
    stage: 'won',
    probability: 100,
    owner: 'Thandi Nkosi',
    nextStep: 'Begin onboarding kickoff',
    expectedCloseDate: '2026-09-01',
    notes:
      'Closed and signed — replaced error-prone Excel invoicing. AI rollout for the finance team scoped next.',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'deal-4',
    name: 'Facilities Maintenance RFP — Bid Response Build',
    companyId: 'comp-4',
    companyName: 'Ekurhuleni Facilities Group (Pty) Ltd',
    contactId: 'cont-4',
    contactName: 'Ayesha Patel',
    amount: 980000,
    stage: 'qualified',
    probability: 40,
    owner: 'Karabo Molefe',
    nextStep: 'Send compliance questionnaire',
    expectedCloseDate: '2026-11-20',
    notes: 'Discovery call completed. Requirement doc needed before proposal.',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'deal-5',
    name: 'Fixed Asset Register Health Check',
    companyId: 'comp-2',
    companyName: 'Lethabo Infrastructure (Pty) Ltd',
    contactId: 'cont-2',
    contactName: 'Pieter van der Merwe',
    amount: 120000,
    stage: 'lead',
    probability: 25,
    owner: 'Thandi Nkosi',
    nextStep: 'Qualify scope — two sites, roughly 800 assets',
    expectedCloseDate: '2026-12-05',
    notes: 'Inbound inquiry after their finance workflow review.',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
]

export const SEED_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    dealId: 'deal-1',
    contactId: 'cont-1',
    type: 'meeting',
    title: 'Executive alignment call with Naledi Mokoena',
    description:
      'Reviewed the compliance matrix and bid-readiness report. Agreed the returnables checklist for the DWS submission.',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    completed: true,
  },
  {
    id: 'act-2',
    dealId: 'deal-2',
    contactId: 'cont-2',
    type: 'email',
    title: 'Sent formal proposal document',
    description: 'Shared custom proposal created with Zanostack Docs.',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    completed: true,
  },
  {
    id: 'act-3',
    dealId: 'deal-4',
    contactId: 'cont-4',
    type: 'task',
    title: 'Draft compliance questionnaire response',
    description: 'Need to complete CIDB grading and SARS TCS verification answers for Ayesha.',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    completed: false,
  },
]
